1. Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй — числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец — это признак, а строка — наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.
2. Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.
3. Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N — число наблюдений.
4. Число, которое мы получили в конце задания 3, является ковариацией двух признаков, содержащихся в массиве а. В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь: https://studopedia.ru/9_153900_viborochnaya-kovariatsiya-i-viborochnaya-dispersiya.html
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом — с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив a. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.
5. Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский']. Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: [1, 1, 1, 2, 2, 3, 3], ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], [450, 300, 350, 500, 450, 370, 290].
6. Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.
7. Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.
8. Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

9. Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака. Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [2]:
import numpy as np

#### №1

In [27]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).T

In [28]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [42]:
mean_a = np.array([[a[:,0].mean(), a[:,1].mean()]]) 

In [43]:
mean_a

array([[2. , 8.4]])

#### №2

In [50]:
a_centered = a - mean_a

In [51]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

#### №3

In [55]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

In [56]:
a_centered_sp

8.0

In [66]:
answer3 = a_centered_sp / (a[:,0].size - 1)

In [67]:
answer3

2.0

#### №4 

In [69]:
cov_matrix = np.cov(a.T)

In [70]:
answer4 = cov_matrix[0, 1]

In [71]:
answer4

2.0

#### №5

In [72]:
import pandas as pd

In [116]:
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Туренев', 'Чехов', 'Островский']
})

In [117]:
book = pd.DataFrame({
    'author_id' : [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети','Рудин','Дворянское гнездо','Толстый и тонкий',
                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
})

In [118]:
authors

author_id author_name
0          1     Туренев
1          2       Чехов
2          3  Островский

In [119]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

#### №6

In [120]:
author_price = pd.merge(authors, book, on='author_id', how='inner')

In [121]:
author_price

author_id author_name            book_title  price
0          1     Туренев           Отцы и дети    450
1          1     Туренев                 Рудин    300
2          1     Туренев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

#### №7

In [122]:
top5 = author_price.nlargest(5, 'price')

In [123]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1     Туренев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1     Туренев  Дворянское гнездо    350

#### №8

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [132]:
group = author_price.groupby('author_name')

In [134]:
authors_stat = group.agg({'price': ['min', 'max', 'mean']})

In [135]:
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Туренев       300  450  366.666667
Чехов         450  500  475.000000

#### №9

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги — твердая или мягкая. В этот столбец поместите данные из следующего списка: ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']. Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака. Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться «твердая» и «мягкая», а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy. Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [133]:
author_price

author_id author_name            book_title  price
0          1     Туренев           Отцы и дети    450
1          1     Туренев                 Рудин    300
2          1     Туренев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [139]:
author_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [140]:
author_price

author_id author_name            book_title  price    cover
0          1     Туренев           Отцы и дети    450  твердая
1          1     Туренев                 Рудин    300   мягкая
2          1     Туренев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [142]:
?pd.pivot_table

In [143]:
book_info = pd.pivot_table(author_price, values = 'price', index=['author_name'], columns=['cover'], aggfunc=np.sum)

In [144]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Туренев       650.0    450.0
Чехов           NaN    950.0

In [147]:
book_info.fillna(0, inplace=True)

In [148]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Туренев       650.0    450.0
Чехов           0.0    950.0

In [150]:
book_info.to_pickle('book_info.pkl')

In [151]:
book_info2 = pd.read_pickle('book_info.pkl')

In [152]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Туренев        True     True
Чехов          True     True